package utilities

import "github.com/nirupamyashas/Gator-Scheduler/server/models"

const SampleToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvdyI6dHJ1ZSwibWVzc2FnZSI6IlN1Y2Nlc3MiLCJ1c2VyZGF0YSI6eyJlbWFpbCI6Im5pcnVwYW15YXNoYXNAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoiWWFzaGFzIiwiaWQiOiJhZGRmNTdlOS03NjI2LTQ0MDYtYTM5Zi1hMWVjYTAzOWVmYjAiLCJpc2FkbWluIjp0cnVlLCJsYXN0bmFtZSI6Ikt1Y2hpbWFuY2hpIiwicGFzc3dvcmQiOiJwYXNzd29yZCJ9fQ.wvTmYSNQZAFtL2aOvw-cN8B7TQrIDMjuCOkjnbhltRg"

const SecretKey = "secret"

var App models.App
